#!/usr/bin/env sh

pgrep -x dunst > /dev/null || dunst &
systemctl --user start polybar.service
systemctl --user start bspwm.service

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 4
bspc config window_gap 40
bspc config top_padding 10

bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config normal_border_color "#130A20"
bspc config focused_border_color "#D0996E"

bspc rule -a "firefox:Toolkit" state=floating border=off sticky=on rectangle=600x400+3250+1200
