#!/usr/bin/env sh

if [ -x ~/.fehbg ]; then ~/.fehbg; fi

pgrep -x dunst > /dev/null || dunst &
systemctl --user start polybar.service
systemctl --user start bspwm.service

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

primary_resolution="$(xrandr | grep 'primary' | awk '{ print $4 }')"
if [[ "$primary_resolution" = "1366x"* ]]; then
  bspc config split_ratio 0.60
  bspc config border_width 2
  bspc config window_gap 5
else
  bspc config split_ratio 0.50
  bspc config border_width 4
  bspc config window_gap 40
fi
bspc config top_padding 10

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config normal_border_color "#130A20"
bspc config focused_border_color "#D0996E"

bspc rule -a "firefox:Toolkit" state=floating border=off sticky=on rectangle=600x400+3250+1200
